from comaze_gym.env.communication_channel import *
from comaze_gym.env.comaze_gym_env import CoMazeGymEnv7x7Sparse, CoMazeGymEnv7x7Dense, CoMazeGymEnv7x7DenseSinglePlayerReward
from comaze_gym.env.comaze_gym_env import CoMazeGymEnv7x7DenseLevel4, CoMazeGymEnv7x7DenseSinglePlayerRewardLevel4, CoMazeGymEnv7x7DenseSinglePlayerRewardLevel4FixedSecretGoalRules 
from comaze_gym.env.comaze_gym_env import CoMazeGymEnv7x7DenseLevel5, CoMazeGymEnv9x9DenseLevel5, CoMazeGymEnv9x9DenseLevel5EasySecrets, CoMazeGymEnv9x9DenseLevel5HardSecrets, CoMazeGymEnv9x9DenseLevel5UniformSecrets
from comaze_gym.env.comaze_gym_env import CoMazeGymEnv7x7DenseFixedActions, CoMazeGymEnv7x7DenseSinglePlayer, CoMazeGymEnv7x7DenseEasySinglePlayer
from comaze_gym.env.comaze_gym_env import CoMazeGymEnv11x11Sparse, CoMazeGymEnv11x11Dense